#!/bin/sh

sudo apt-get -y build-dep dwm

sudo apt-get -y install \
	fonts-dejavu \
	fonts-materialdesignicons-webfont \
	lightdm \
	suckless-tools \
	xserver-xorg-input-libinput \
	zzuf

# touchpad
sudo mkdir -p /etc/X11/xorg.conf.d
sudo cp $HOME/.materialize/artifacts/dwm/95-touchpad.conf /etc/X11/xorg.conf.d/

# tabbed
if cd $HOME/code/tabbed; then
	git pull
else
	git clone https://github.com/schachmat/tabbed $HOME/code/tabbed
	cd $HOME/code/tabbed
fi
git checkout config
make
make PREFIX=$HOME install
cd -

# dwm
if cd $HOME/code/dwm; then
	git pull
else
	git clone https://github.com/schachmat/dwm $HOME/code/dwm
	cd $HOME/code/dwm
fi
git checkout config
make
make PREFIX=$HOME install
cd -

# lightdm
sudo mkdir -p /etc/lightdm/lightdm.conf.d/
cat <<DOG | sudo tee /etc/lightdm/lightdm.conf.d/autologin.conf >/dev/null
[Seat:*]
autologin-user=${USER}
DOG
