#!/bin/sh

sudo apt-get -y install gsettings-desktop-schemas

gsettings set org.gnome.desktop.peripherals.mouse accel-profile "'flat'"
gsettings set org.gnome.desktop.interface color-scheme "'prefer-dark'"
gsettings set org.gnome.desktop.interface clock-format "'24h'"

gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled "true"
gsettings set org.gnome.settings-daemon.plugins.color night-light-schedule-automatic "false"
gsettings set org.gnome.settings-daemon.plugins.color night-light-schedule-from "23"
gsettings set org.gnome.settings-daemon.plugins.color night-light-schedule-to "5"
gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature "3700"

# Disable unwanted gnome shell extensions
gsettings set org.gnome.shell enabled-extensions "$( \
gsettings get org.gnome.shell enabled-extensions | sed \
	-e "s/'apps-menu@gnome-shell-extensions.gcampax.github.com'//g" \
	-e "s/'dash-to-panel@jderose9.github.com'//g" \
	-e "s/'launch-new-instance@gnome-shell-extensions.gcampax.github.com'//g" \
	-e "s/'ubuntu-appindicators@ubuntu.com'//g" \
	-e 's/, *,/, /g' \
	-e 's/\[[, ]*/[/g' \
	-e 's/[, ]*]/]/g' \
)"

# Configure gnome-terminal color scheme in default profile
PROFILE_UUID=$(gsettings get org.gnome.Terminal.ProfilesList default | tr -d "'")
SCHEMA="org.gnome.Terminal.Legacy.Profile"
PROFILE_PATH="/org/gnome/terminal/legacy/profiles:/:${PROFILE_UUID}/"
SCHEMA_PATH="${SCHEMA}:${PROFILE_PATH}"

PALETTE="[\
'#181849495656', '#fafa57575050', '#7575b9b93838', '#dbdbb3b32d2d', \
'#46469595f7f7', '#f2f27575bebe', '#4141c7c7b9b9', '#727289898f8f', \
'#2d2d5b5b6969', '#ffff66665c5c', '#8484c7c74747', '#ebebc1c13d3d', \
'#5858a3a3ffff', '#ffff8484cdcd', '#5353d6d6c7c7', '#cacad8d8d9d9']"

gsettings set "$SCHEMA_PATH" palette "$PALETTE"
gsettings set "$SCHEMA_PATH" foreground-color "'#adadbcbcbcbc'"
gsettings set "$SCHEMA_PATH" background-color "'#10103c3c4848'"
gsettings set "$SCHEMA_PATH" bold-color "'#cacad8d8d9d9'"
gsettings set "$SCHEMA_PATH" bold-color-same-as-fg "false"
gsettings set "$SCHEMA_PATH" use-theme-colors "false"

# Configure automatic dark mode switcher for gnome-terminal based on system
# setting
systemctl --user daemon-reload
systemctl --user enable --now gnome-terminal-theme-watcher.service
