#!/bin/sh

sudo apt-get -y install gsettings-desktop-schemas

gsettings set org.gnome.desktop.interface enable-hot-corners "false"
gsettings set org.gnome.mutter dynamic-workspaces "false"
gsettings set org.gnome.desktop.wm.preferences num-workspaces "1"
gsettings set org.gnome.desktop.peripherals.mouse accel-profile "'flat'"
gsettings set org.gnome.desktop.interface gtk-theme "'Adwaita'"
gsettings set org.gnome.desktop.interface clock-format "'24h'"

gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled "true"
gsettings set org.gnome.settings-daemon.plugins.color night-light-schedule-automatic "false"
gsettings set org.gnome.settings-daemon.plugins.color night-light-schedule-from "23"
gsettings set org.gnome.settings-daemon.plugins.color night-light-schedule-to "5"
gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature "3700"

# Disable unwanted gnome shell extensions
gsettings set org.gnome.shell enabled-extensions "$( \
gsettings get org.gnome.shell enabled-extensions | sed \
	-e "s/'apps-menu@gnome-shell-extensions.gcampax.github.com'//g" \
	-e "s/'dash-to-panel@jderose9.github.com'//g" \
	-e "s/'launch-new-instance@gnome-shell-extensions.gcampax.github.com'//g" \
	-e "s/'ubuntu-appindicators@ubuntu.com'//g" \
	-e 's/, *,/, /g' \
	-e 's/\[[, ]*/[/g' \
	-e 's/[, ]*]/]/g' \
)"

# Configure gnome-terminal color scheme in default profile
PROFILE_UUID=$(gsettings get org.gnome.Terminal.ProfilesList default | tr -d "'")
SCHEMA="org.gnome.Terminal.Legacy.Profile"
PROFILE_PATH="/org/gnome/terminal/legacy/profiles:/:${PROFILE_UUID}/"
SCHEMA_PATH="${SCHEMA}:${PROFILE_PATH}"

gsettings set "$SCHEMA_PATH" bold-color-same-as-fg "false"
gsettings set "$SCHEMA_PATH" use-theme-colors "false"

# Configure automatic dark mode switcher for gnome-terminal based on system
# setting. Applies correct theme immediately on startup too.
systemctl --user daemon-reload
systemctl --user enable --now gnome-terminal-theme-watcher.service
