#!/bin/sh

sudo apt-get -y install \
	console-setup \
	kbd \
	keyboard-configuration

# apply xkb hacks
for file in rules/base rules/base.xml rules/base.lst rules/evdev rules/evdev.xml rules/evdev.lst types/complete; do
	src=$HOME/.materialize/artifacts/neo/xkb/$file
	dst=/usr/share/X11/xkb/$file
	# If we know the file from /usr, replace it with our own
	cmp --silent $src.dpkg-dist $dst \
		&& sudo cp $src $dst

	if ! cmp $src $dst; then
		echo ffs, xkb-data was updated again. update ~/.materialize/artifacts/neo/xkb/ and try again...
		exit 1
	fi
done
sudo cp $HOME/.materialize/artifacts/neo/xkb/symbols/mate /usr/share/X11/xkb/symbols/mate
sudo cp $HOME/.materialize/artifacts/neo/xkb/types/mate /usr/share/X11/xkb/types/mate

# keymap
sudo mv /etc/default/keyboard /etc/default/keyboard.mate
sudo dpkg-reconfigure --frontend=noninteractive keyboard-configuration
cmp --silent /etc/default/keyboard /etc/default/keyboard.mate \
	&& sudo rm /etc/default/keyboard.mate \
	|| sudo mv /etc/default/keyboard.mate /etc/default/keyboard.bak

# configure boottime keymap
gzip <$HOME/.materialize/artifacts/neo/boottime-kmap | sudo tee /etc/console-setup/boottime.kmap.gz >/dev/null

sudo cp $HOME/.materialize/artifacts/neo/initramfs-hook /etc/initramfs-tools/hooks/neo
sudo chmod +x /etc/initramfs-tools/hooks/neo

sudo sed -i 's|^KEYMAP=.*$|KEYMAP=y|' /etc/initramfs-tools/initramfs.conf
if ! grep -q '^KEYMAP=y$' /etc/initramfs-tools/initramfs.conf; then
	sudo sed -i '$ a\KEYMAP=y' /etc/initramfs-tools/initramfs.conf >/dev/null
fi

sudo update-initramfs -u -k all 2>&1 | grep -v '^WARNING: Unknown key type'
