#!/bin/sh

sudo apt-get -y install \
	cargo \
	console-setup \
	gnome-settings-daemon-common \
	gnome-shell-common \
	kbd \
	keyboard-configuration \
	libglib2.0-bin \
	mutter-common

cargo install --locked xremap --features gnome

# Make xremap available for root (yeah, we should probably get it packaged
# properly).
sudo ln --symbolic --force $HOME/.cargo/bin/xremap /usr/local/bin/xremap

sudo install --mode=644 $HOME/.materialize/artifacts/neo/xremap.yml /etc/xremap.yml
sudo install --mode=644 $HOME/.materialize/artifacts/neo/xremap.service /etc/systemd/system/xremap.service
sudo systemctl daemon-reload
sudo systemctl enable --now xremap.service

# keymap
sudo mv /etc/default/keyboard /etc/default/keyboard.mate
sudo dpkg-reconfigure --frontend=noninteractive keyboard-configuration
cmp --silent /etc/default/keyboard /etc/default/keyboard.mate \
	&& sudo rm /etc/default/keyboard.mate \
	|| sudo mv /etc/default/keyboard.mate /etc/default/keyboard.bak

# gnome configuration
if dpkg -s gsettings-desktop-schemas &>/dev/null; then
	gsettings set org.gnome.desktop.input-sources xkb-options "[]"
	gsettings set org.gnome.desktop.wm.keybindings switch-applications "[]"
	gsettings set org.gnome.desktop.wm.keybindings switch-applications-backward "[]"
	gsettings set org.gnome.desktop.wm.keybindings switch-windows "['<Alt>Tab','<Alt>l']"
	gsettings set org.gnome.desktop.wm.keybindings switch-windows-backward "['<Alt><Shift>Tab','<Alt><Shift>l']"
	gsettings set org.gnome.settings-daemon.plugins.media-keys screensaver "['<Alt>q']"
	gsettings set org.gnome.shell.keybindings toggle-application-view "['<Alt>a']"
	gsettings set org.gnome.mutter overlay-key ""
fi

# configure boottime keymap
gzip <$HOME/.materialize/artifacts/neo/boottime-kmap | sudo tee /etc/console-setup/boottime.kmap.gz >/dev/null

sudo install --mode=755 $HOME/.materialize/artifacts/neo/initramfs-hook /etc/initramfs-tools/hooks/neo
sudo chmod +x /etc/initramfs-tools/hooks/neo

sudo sed -i 's|^KEYMAP=.*$|KEYMAP=y|' /etc/initramfs-tools/initramfs.conf
if ! grep -q '^KEYMAP=y$' /etc/initramfs-tools/initramfs.conf; then
	sudo sed -i '$ a\KEYMAP=y' /etc/initramfs-tools/initramfs.conf >/dev/null
fi

sudo update-initramfs -u -k all 2>&1 | grep -v '^WARNING: Unknown key type'
