#!/bin/sh

sudo apt-get -y install \
	git \
	libgit2-dev \
	pkg-config

if cd $HOME/code/slcp; then
	git pull
else
	git clone https://github.com/schachmat/slcp.git $HOME/code/slcp
	cd $HOME/code/slcp
	make
	sed -i "s|BLUE|$(echo -e 'RED\nGREEN\nYELLOW\nBLUE\nMAGENTA' | shuf | head -n 1)|" config.h
fi
make
make PREFIX=$HOME install
cd -

