#!/bin/sh

# for alacritty: install xclip, cargo, cmake
sudo apt-get -y install rxvt-unicode-256color


mkdir -p $HOME/.urxvt/ext
ln -sf /usr/lib/x86_64-linux-gnu/urxvt/perl/font-size $HOME/.urxvt/ext/font-size
